---
- name: Configure Network Interfaces with systemd-networkd
  hosts: all
  tasks:
    - name: Configure manual interfaces
      copy:
        src: files/networkd/
        dest: /etc/systemd/network/
        mode: 0644
    - name: Create netdev
      template:
        src: tun.netdev.j2
        dest: "/etc/systemd/network/30-{{ item.interface }}.netdev"
        mode: 0644
      notify: Restart systemd-networkd
      loop: "{{ peers }}"
      loop_control:
        label: "{{ item.name }}"
    - name: Create network
      template:
        src: tun.network.j2
        dest: "/etc/systemd/network/30-{{ item.interface }}.network"
        mode: 0644
      notify: Restart systemd-networkd
      loop: "{{ peers }}"
      loop_control:
        label: "{{ item.name }}"

  handlers:
    - name: Restart systemd-networkd
      service:
        name: systemd-networkd
        state: restarted




